### ISSUE TITLE
unhandled null pointer dereference :)

### ISSUE THREAD

**Issue by kotee4ko** [psifertex/callgraph#1]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/binaryninja/plugins/../python/binaryninja/plugin.py", line 741, in run
    self.task.run()
  File "/home/c4t/.binaryninja/plugins/callgraph/__init__.py", line 11, in run
    collect_calls(self.view, self.rootfunction)
  File "/home/c4t/.binaryninja/plugins/callgraph/__init__.py", line 62, in collect_calls
    if (call_il.operation in (
AttributeError: 'NoneType' object has no attribute 'operation'
```

as I can understand - not all functions have xrefs since we are in static analyze.

```
 56     for function in view.functions:
 57         for ref in view.get_code_refs(function.start):
 58             caller = ref.function
 59             calls[function] = calls.get(function, set())
 60
 61             call_il = caller.get_low_level_il_at(ref.address)
 62             if (call_il.operation in (
 63                         LowLevelILOperation.LLIL_CALL,
 64                         LowLevelILOperation.LLIL_TAILCALL,
 65                         LowLevelILOperation.LLIL_CALL_STACK_ADJUST
 66                     ) and call_il.dest.operation == LowLevelILOperation.LLIL_CONST_PTR):
 67                 calls[function].add(caller)
```

maybe, there are some additional checks needed?

Tthanks.

**Comment by kotee4ko** [comment]
it's seems that I was able to fix this via adding:
```
 61             call_il = caller.get_low_level_il_at(ref.address)
 +62            if not call_il:
 +63                continue
 64             if (call_il.operation in (
 65                         LowLevelILOperation.LLIL_CALL,
 66                         LowLevelILOperation.LLIL_TAILCALL,
 67                         LowLevelILOperation.LLIL_CALL_STACK_ADJUST
 68                     ) and call_il.dest.operation == LowLevelILOperation.LLIL_CONST_PTR):
 69                 calls[function].add(caller)

```
